apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: houwayda/test:2a3d044264a5e9a93a1f44682fdfedf42d5f9f1d
          imagePullPolicy: Always
          ports:
            - containerPort: 80
