apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: houwayda/test:394536fc51e9019b292abfaec27a532bd1831e49
          imagePullPolicy: Always
          ports:
            - containerPort: 80
