apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: houwayda/test:f7f8e85c1c8de04e50d5fe0870d5d954917e441e
          imagePullPolicy: Always
          ports:
            - containerPort: 80
